defaultSemverRangePrefix: ""

enableGlobalCache: false

nmMode: hardlinks-global

nodeLinker: node-modules

packageExtensions:
  apollo-server-micro@*:
    peerDependencies:
      graphql: ^15.6.1 || ^16.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-3.2.0-rc.5.cjs
